### ISSUE TITLE
Index .braavos.stark and Xplorer 

### ISSUE THREAD

**Issue by fricoben** [lfglabs-dev/indexer_old#22]
https://app.starknet.id/api/indexer/addrs_to_domains
https://app.starknet.id/api/indexer/addr_to_domain
https://app.starknet.id/api/indexer/domain_to_addr 

Do not support .braavos.stark domain, we should add the support of it

**Comment by Th0rgal** [comment]
Are you sure @fricoben ? addr_to_domain should be the same for custom resolvers since it's part of the naming contract.
It would make sense for domain_to_addr though, but it might require a projection

**Comment by Th0rgal** [comment]
tried it, looks good to me
